baseurl = "/"
title = "blog.dima23"
copyright = "Â© dima 2018"
canonifyurls = true
languageCode = "en-US"
paginate = 5
theme = "hugo-dusk"

#googleAnalytics = ""
#disqusShortname = ""

[author]
  name = "dvogt"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "vim" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "web"
  weight = -120
  identifier = "web"
  url = "https://dima23.de"

[[menu.main]]
  name = "tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[[menu.main]]
  name = "rss"
  weight = -100
  identifier = "rss"
  url = "/index.xml"

[params.meta]
  keywords = "blog, tech, develop, software, coding"
  description = "personal developer blog for some coding notes."

[params]
  pagetitle = "Some notes"
  #firstline = "These posts are for my personal usage. Be careful if copy something."
  #github = "dvogt23"
  #gitlab = "gitlab id"
  #twitter = "dtri23"
  #linkedin = "dimitri-vogt-096555155"
  #email = "myemail"

[params.colors]
  # hugo-dusk colors
  background = "#202020" # background color for the site
  main = "#B3B6B7"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color

enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
